In [1]:
import pandas as pd
import numpy as np
import os 
import datetime

## Explain
This notebook is joining all the csv files from the openmeteo requests into a singular one to processing.

It is part of the processing chain to Predict GLobal anomaly monthly temperature. 

This preprocessing part joing the different csv and also process that dataset to be a Tensor structure ready for further NN models.

-- NOTE: READ UNIFIED PIPELINE

In [2]:
folder = "/home/camarada/Documents/projects/temp-grss-nasa/data_/ecmwf_temp_openmeteo"
df = pd.read_csv(os.path.join(folder,'ecmwf_weather_batch_0_60.csv'))

## convert to date
df['date'] = pd.to_datetime(df['date'])

## create a day-month-year column
df['dmy'] = df['date'].dt.date

print(df.shape)
## filter a wrong value
df = df.loc[(df['dmy']>=datetime.date(2023, 1, 1)) & (df['dmy']<=datetime.date(2025, 12, 31))]

print(df.shape)

(67620, 6)
(65760, 6)

In [3]:
df.tail()

,date,capital,avg_temp_c,latitude,longitude,dmy
67585,2025-12-27 21:00:00+00:00,Antananarivo,20.564580,-18.945518,47.527092,2025-12-27
67586,2025-12-28 21:00:00+00:00,Antananarivo,20.050001,-18.945518,47.527092,2025-12-28
67587,2025-12-29 21:00:00+00:00,Antananarivo,21.506250,-18.945518,47.527092,2025-12-29
67588,2025-12-30 21:00:00+00:00,Antananarivo,20.497920,-18.945518,47.527092,2025-12-30
67589,2025-12-31 21:00:00+00:00,Antananarivo,19.462500,-18.945518,47.527092,2025-12-31

In [4]:
folder = "/home/camarada/Documents/projects/temp-grss-nasa/data_/ecmwf_temp_openmeteo"
df2 = pd.read_csv(os.path.join(folder,'ecmwf_weather_batch_60_117.csv'))

df2['date'] = pd.to_datetime(df2['date'])

## create a day-month-year column
df2['dmy'] = df2['date'].dt.date

print(df2.shape)
## filter a wrong value
df2 = df2.loc[(df2['dmy']>=datetime.date(2023, 1, 1)) & (df2['dmy']<=datetime.date(2025, 12, 31))]
    
print(df2.shape)

(64239, 6)
(62472, 6)

In [5]:
df2.tail()

,date,capital,avg_temp_c,latitude,longitude,dmy
64203,2025-12-27 04:00:00+00:00,San Juan,24.266663,18.453426,-66.13504,2025-12-27
64204,2025-12-28 04:00:00+00:00,San Juan,23.610415,18.453426,-66.13504,2025-12-28
64205,2025-12-29 04:00:00+00:00,San Juan,23.502080,18.453426,-66.13504,2025-12-29
64206,2025-12-30 04:00:00+00:00,San Juan,24.635416,18.453426,-66.13504,2025-12-30
64207,2025-12-31 04:00:00+00:00,San Juan,25.308334,18.453426,-66.13504,2025-12-31

In [6]:
folder = "/home/camarada/Documents/projects/temp-grss-nasa/data_/ecmwf_temp_openmeteo"
df3 = pd.read_csv(os.path.join(folder,'ecmwf_weather_batch_0_117_2020-01-01_2022-12-31.csv'))

df3['date'] = pd.to_datetime(df3['date'])

## create a day-month-year column
df3['dmy'] = df3['date'].dt.date

print(df3.shape)
## filter a wrong value
df3 = df3.loc[df3['dmy']>=datetime.date(2020, 1, 1)]

print(df3.shape)

(128232, 6)
(128143, 6)

In [7]:
df3.head()

,date,capital,avg_temp_c,latitude,longitude,dmy
1,2020-01-01 23:00:00+00:00,Andorra la Vella,6.206417,42.425304,1.453745,2020-01-01
2,2020-01-02 23:00:00+00:00,Andorra la Vella,6.237666,42.425304,1.453745,2020-01-02
3,2020-01-03 23:00:00+00:00,Andorra la Vella,4.843917,42.425304,1.453745,2020-01-03
4,2020-01-04 23:00:00+00:00,Andorra la Vella,6.425167,42.425304,1.453745,2020-01-04
5,2020-01-05 23:00:00+00:00,Andorra la Vella,5.808500,42.425304,1.453745,2020-01-05

In [8]:
folder = "/home/camarada/Documents/projects/temp-grss-nasa/data_/ecmwf_temp_openmeteo"
df4 = pd.read_csv(os.path.join(folder,'ecmwf_weather_batch_0_117_2017-01-01_2019-12-31.csv'))
df4['date'] = pd.to_datetime(df4['date'])

## create a day-month-year column
df4['dmy'] = df4['date'].dt.date

print(df4.shape)
## filter a wrong value
df4 = df4.loc[df4['dmy']>=datetime.date(2017, 1, 1)]

print(df4.shape)

(128115, 6)
(128026, 6)

In [9]:
df4.tail()

,date,capital,avg_temp_c,latitude,longitude,dmy
128110,2019-12-27 04:00:00+00:00,San Juan,25.393751,18.453426,-66.13504,2019-12-27
128111,2019-12-28 04:00:00+00:00,San Juan,25.516668,18.453426,-66.13504,2019-12-28
128112,2019-12-29 04:00:00+00:00,San Juan,25.077085,18.453426,-66.13504,2019-12-29
128113,2019-12-30 04:00:00+00:00,San Juan,25.208336,18.453426,-66.13504,2019-12-30
128114,2019-12-31 04:00:00+00:00,San Juan,25.404167,18.453426,-66.13504,2019-12-31

In [9]:
## save all concat file into a unified parquet ecmwf
## concat boths
concat = pd.concat([df, df2, df3, df4], axis=0)

## create a new column YEAR-MONTH
concat['month_year']=pd.to_datetime(concat['date']).dt.strftime("%Y-%m")

## convert all capitals to lower
concat['capital'] = concat['capital'].apply(lambda x:x.lower())

## sort by capital and by date
concat = concat.sort_values(by=['dmy','capital'])

In [13]:
concat.isna().any()

date          False
capital       False
avg_temp_c    False
latitude      False
longitude     False
dmy           False
month_year    False
dtype: bool

In [14]:
## save in a parquet a unified file
concat.to_parquet(
    "/home/camarada/Documents/projects/temp-grss-nasa/data_/ecmwf_temp_openmeteo/ecmwf_temp_daily_2017_31-12-2025.parquet"
)

# Unified Pipeline
- Only needs to fetch the new monthly data from 2026-jan-1 to the target month.
- The parquet from 2017-2025 ranges an unified and verified dataset with all capitals and the current dates. It is to short cut the process of concatening every new data comes from

In [2]:
## load unified parquet
df1725 = pd.read_parquet(
    "/home/camarada/Documents/projects/temp-grss-nasa/data_/ecmwf_temp_openmeteo/ecmwf_temp_daily_2017_31-12-2025.parquet"
)

In [3]:
df1725.tail()

,date,capital,avg_temp_c,latitude,longitude,dmy,month_year
14620,2025-12-31 11:00:00+00:00,wellington,17.481833,-41.300526,174.705887,2025-12-31,2025-12
7858,2025-12-31 22:00:00+00:00,windhoek,21.516668,-22.530756,17.085062,2025-12-31,2025-12
24763,2025-12-31 15:00:00+00:00,yakutsk,-34.277080,61.968365,129.751862,2025-12-31,2025-12
3350,2025-12-31 20:00:00+00:00,yerevan,-0.811833,40.105446,44.495800,2025-12-31,2025-12
46176,2025-12-31 23:00:00+00:00,zagreb,1.070833,45.799648,15.924171,2025-12-31,2025-12

In [4]:
## add here the last month
folder = "/home/camarada/Documents/projects/temp-grss-nasa/data_/ecmwf_temp_openmeteo"
df5 = pd.read_csv(os.path.join(folder,'ecmwf_weather_batch_0_117_2026-01-01_2026-04-30.csv'))
df5['date'] = pd.to_datetime(df5['date'])

## create a day-month-year column
df5['dmy'] = df5['date'].dt.date

print(df5.shape)
## filter a wrong value
df5 = df5.loc[(df5['dmy']>=datetime.date(2026, 1, 1))]

print(df5.shape)

(14040, 6)
(13948, 6)

In [5]:
## concat boths
concat = pd.concat([df1725, df5], axis=0)

## create a new column YEAR-MONTH
concat['month_year']=pd.to_datetime(concat['date']).dt.strftime("%Y-%m")

## convert all capitals to lower
concat['capital'] = concat['capital'].apply(lambda x:x.lower())

## sort by capital and by date
concat = concat.sort_values(by=['dmy','capital'])

In [6]:
concat['capital'].unique().shape

(117,)

In [7]:
concat.shape

(398349, 7)

In [10]:
concat.tail()

,date,capital,avg_temp_c,latitude,longitude,dmy,month_year
12239,2026-04-30 06:00:00+00:00,san salvador,25.128916,13.673111,-89.174316,2026-04-30,2026-04
2279,2026-04-30 04:00:00+00:00,santiago,16.535418,-33.427067,-70.642761,2026-04-30,2026-04
3479,2026-04-30 04:00:00+00:00,santo domingo,24.737581,18.523726,-69.902039,2026-04-30,2026-04
1439,2026-04-30 04:00:00+00:00,sucre,13.055667,-19.086117,-65.212250,2026-04-30,2026-04
11279,2026-04-30 04:00:00+00:00,"washington, d.c.",14.397915,38.910366,-77.072510,2026-04-30,2026-04

In [11]:
## save the aggregate in a parquet file 
outfolder = "/home/camarada/Documents/projects/temp-grss-nasa/data_/ecmwf_temp_openmeteo"
filename = "ecmwf_temperature_daily_avg_2017-2026april.parquet"
concat.to_parquet(os.path.join(outfolder,filename))

In [37]:
concat.head()

,date,capital,avg_temp_c,latitude,longitude,dmy,month_year
122641,2017-01-01 20:00:00+00:00,abu dhabi,22.168749,24.428822,54.364998,2017-01-01,2017-01
73366,2017-01-01 23:00:00+00:00,abuja,25.954168,9.033392,7.474049,2017-01-01,2017-01
35041,2017-01-01 21:00:00+00:00,addis ababa,12.097917,9.033392,38.771626,2017-01-01,2017-01
107311,2017-01-01 23:00:00+00:00,algiers,9.854834,36.731106,3.070866,2017-01-01,2017-01
54751,2017-01-01 21:00:00+00:00,amman,5.416084,31.950790,35.891567,2017-01-01,2017-01

## NASA Global anomaly montlhy

Nasa dataset

In [14]:
df_nasa = pd.read_csv('/home/camarada/Documents/projects/temp-grss-nasa/data_/nasa/1981-2025.csv')

In [15]:
df_long = df_nasa.melt(id_vars=['Year'], var_name='Month', value_name='Value')

df_long['Date'] = pd.to_datetime(df_long['Year'].astype(str) + df_long['Month'], format='%Y%b')

# 3. Clean up: Sort by date and set it as the index
df_ts = df_long.sort_values('Date').set_index('Date').drop(columns=['Year', 'Month'])

df_ts.reset_index(inplace=True)

## create a new column YEAR-MONTH
df_ts['month_year']=pd.to_datetime(df_ts['Date']).dt.strftime("%Y-%m")

## apply scaler to celsius
df_ts['Value'] = df_ts['Value']/ 100

df_ts = df_ts.dropna(axis=0)
df_ts.tail()

          Date  Value month_year
538 2025-11-01   1.21    2025-11
539 2025-12-01   1.05    2025-12
540 2026-01-01   1.08    2026-01
541 2026-02-01   1.24    2026-02
542 2026-03-01   1.28    2026-03

## Create dataset structure

This is a ready structure to be passed into a tensor

In [21]:
## filter the concat before the 2026-01-01 since there is no true data for this period
concat2325 = concat.loc[concat['dmy']<datetime.date(2026,3,1)]
concat26 = concat.loc[concat['dmy']>=datetime.date(2026,3,1)]

In [19]:
concat2325.sort_values(by=['dmy','capital']).tail()

,date,capital,avg_temp_c,latitude,longitude,dmy,month_year
8671,2026-01-31 12:00:00+00:00,wellington,16.883917,-41.300526,174.705887,2026-01-31,2026-01
7951,2026-01-31 22:00:00+00:00,windhoek,21.941668,-22.530756,17.085062,2026-01-31,2026-01
9751,2026-01-31 15:00:00+00:00,yakutsk,-34.902080,61.968365,129.751862,2026-01-31,2026-01
271,2026-01-31 20:00:00+00:00,yerevan,3.017333,40.105446,44.495800,2026-01-31,2026-01
12031,2026-01-31 22:00:00+00:00,zagreb,2.933334,45.799648,15.924171,2026-01-31,2026-01

In [22]:
%%time
### Create arrays and save as npz

## root_dir =
root_dir = os.getcwd()
n_capitals = 117  # number of capitals
n_timepoints = 31  # days

uniq_capital = concat2325['capital'].unique()
month_years = concat2325['month_year'].unique()
n_samples = len(month_years)

## IMPORTANT
## sort by capital name
concat2325 = concat2325.sort_values(by=['dmy','capital']).copy()

# Pre-allocate arrays
temp_matrices = np.zeros((n_samples, n_capitals, n_timepoints), dtype=np.float32)
masks = np.zeros((n_samples, n_capitals, n_timepoints), dtype=np.float32)
labels = np.zeros(n_samples, dtype=np.float32)
month_year_list = []

for idx, my in enumerate(month_years):
    print(f"Processing: {my}")

    try:
        # Get data for this month/year
        month_data = concat2325[concat2325['month_year'] == my]

        for i, capital in enumerate(uniq_capital):
            capital_data = month_data[month_data['capital'] == capital].sort_values('dmy')
            temp_values = capital_data['avg_temp_c'].values

            if len(temp_values) > 0:
                temp_matrices[idx, i, :len(temp_values)] = temp_values
                masks[idx, i, :len(temp_values)] = 1.0

        # Get the true anomaly
        anomaly_value = df_ts[df_ts['month_year'] == my]['Value'].values[0]
        labels[idx] = anomaly_value
        month_year_list.append(my)
    except Exception as e:
        print(f"Couldnt process: {my}")

Processing: 2017-01
Processing: 2017-02
Processing: 2017-03
Processing: 2017-04
Processing: 2017-05
Processing: 2017-06
Processing: 2017-07
Processing: 2017-08
Processing: 2017-09
Processing: 2017-10
Processing: 2017-11
Processing: 2017-12
Processing: 2018-01
Processing: 2018-02
Processing: 2018-03
Processing: 2018-04
Processing: 2018-05
Processing: 2018-06
Processing: 2018-07
Processing: 2018-08
Processing: 2018-09
Processing: 2018-10
Processing: 2018-11
Processing: 2018-12
Processing: 2019-01
Processing: 2019-02
Processing: 2019-03
Processing: 2019-04
Processing: 2019-05
Processing: 2019-06
Processing: 2019-07
Processing: 2019-08
Processing: 2019-09
Processing: 2019-10
Processing: 2019-11
Processing: 2019-12
Processing: 2020-01
Processing: 2020-02
Processing: 2020-03
Processing: 2020-04
Processing: 2020-05
Processing: 2020-06
Processing: 2020-07
Processing: 2020-08
Processing: 2020-09
Processing: 2020-10
Processing: 2020-11
Processing: 2020-12
Processing: 2021-01
Processing: 2021-02
Processing: 2021-03
Processing: 2021-04
Processing: 2021-05
Processing: 2021-06
Processing: 2021-07
Processing: 2021-08
Processing: 2021-09
Processing: 2021-10
Processing: 2021-11
Processing: 2021-12
Processing: 2022-01
Processing: 2022-02
Processing: 2022-03
Processing: 2022-04
Processing: 2022-05
Processing: 2022-06
Processing: 2022-07
Processing: 2022-08
Processing: 2022-09
Processing: 2022-10
Processing: 2022-11
Processing: 2022-12
Processing: 2023-01
Processing: 2023-02
Processing: 2023-03
Processing: 2023-04
Processing: 2023-05
Processing: 2023-06
Processing: 2023-07
Processing: 2023-08
Processing: 2023-09
Processing: 2023-10
Processing: 2023-11
Processing: 2023-12
Processing: 2024-01
Processing: 2024-02
Processing: 2024-03
Processing: 2024-04
Processing: 2024-05
Processing: 2024-06
Processing: 2024-07
Processing: 2024-08
Processing: 2024-09
Processing: 2024-10
Processing: 2024-11
Processing: 2024-12
Processing: 2025-01
Processing: 2025-02
Processing: 2025-03
Processing: 2025-04
Processing: 2025-05
Processing: 2025-06
Processing: 2025-07
Processing: 2025-08
Processing: 2025-09
Processing: 2025-10
Processing: 2025-11
Processing: 2025-12
Processing: 2026-01
Processing: 2026-02
CPU times: user 1min 33s, sys: 765 ms, total: 1min 34s
Wall time: 1min 41s

In [26]:
## save 
# Save to npz file

## the files are organized by ascendend order given by capital name
np.savez_compressed(
    '/home/camarada/Documents/projects/temp-grss-nasa/data_/openmeteo_tensors/openmeteo-2017-2026fev-temp.npz',
    temp_matrices=temp_matrices,  # shape: (n_samples, n_capitals, n_timepoints)
    masks=masks,                  # shape: (n_samples, n_capitals, n_timepoints)
    labels=labels,                # shape: (n_samples,)
    month_years=np.array(month_year_list),  # shape: (n_samples,)
    capitals=uniq_capital         # shape: (n_capitals,)
)

In [23]:
masks.shape

(110, 117, 31)

In [24]:
labels.shape

(110,)

In [32]:
labels[-1]

np.float32(0.0)

In [33]:
month_year_list[-1]

'2025-12'

In [35]:
anomaly_value

np.float64(1.05)

## Values to be infered

In [27]:
concat26

,date,capital,avg_temp_c,latitude,longitude,dmy,month_year
13500,2026-03-01 20:00:00+00:00,abu dhabi,27.164581,24.428822,54.364998,2026-03-01,2026-03
8100,2026-03-01 23:00:00+00:00,abuja,29.172920,9.033392,7.474049,2026-03-01,2026-03
3900,2026-03-01 21:00:00+00:00,addis ababa,16.837500,9.033392,38.771626,2026-03-01,2026-03
11820,2026-03-01 23:00:00+00:00,algiers,15.867333,36.731106,3.070866,2026-03-01,2026-03
6060,2026-03-01 21:00:00+00:00,amman,8.759833,31.950790,35.891567,2026-03-01,2026-03
...,...,...,...,...,...,...,...
12239,2026-04-30 06:00:00+00:00,san salvador,25.128916,13.673111,-89.174316,2026-04-30,2026-04
2279,2026-04-30 04:00:00+00:00,santiago,16.535418,-33.427067,-70.642761,2026-04-30,2026-04
3479,2026-04-30 04:00:00+00:00,santo domingo,24.737581,18.523726,-69.902039,2026-04-30,2026-04
1439,2026-04-30 04:00:00+00:00,sucre,13.055667,-19.086117,-65.212250,2026-04-30,2026-04
11279,2026-04-30 04:00:00+00:00,"washington, d.c.",14.397915,38.910366,-77.072510,2026-04-30,2026-04

In [28]:
### Create arrays and save as npz

## THere is no labels to save here! 
## Since it is the month to predict the anomaly

## root_dir =
root_dir = os.getcwd()
n_capitals = 117  # number of capitals
n_timepoints = 31  # days

uniq_capital = concat26['capital'].unique()
month_years = concat26['month_year'].unique()
n_samples = len(month_years)

## sort by capital name
concat26 = concat26.sort_values(by=['dmy','capital']).copy()

# Pre-allocate arrays
temp_matrices = np.zeros((n_samples, n_capitals, n_timepoints), dtype=np.float32)
masks = np.zeros((n_samples, n_capitals, n_timepoints), dtype=np.float32)
month_year_list = []

for idx, my in enumerate(month_years):
    print(f"Processing: {my}")

    try:
        # Get data for this month/year
        month_data = concat26[concat26['month_year'] == my]

        for i, capital in enumerate(uniq_capital):
            capital_data = month_data[month_data['capital'] == capital].sort_values('dmy')
            temp_values = capital_data['avg_temp_c'].values

            if len(temp_values) > 0:
                temp_matrices[idx, i, :len(temp_values)] = temp_values
                masks[idx, i, :len(temp_values)] = 1.0


        month_year_list.append(my)
    except Exception as e:
        print(f"Couldnt process: {my}")

Processing: 2026-03

Processing: 2026-04

In [29]:
where = '/home/camarada/Documents/projects/temp-grss-nasa/data_/openmeteo_tensors/'
# Save to npz file
np.savez_compressed(
    os.path.join(where, 'openmeteo-2026-mar-april-temp.npz'),
    temp_matrices=temp_matrices,  # shape: (n_samples, n_capitals, n_timepoints)
    masks=masks,                  # shape: (n_samples, n_capitals, n_timepoints)
    month_years=np.array(month_year_list),  # shape: (n_samples,)
    capitals=uniq_capital         # shape: (n_capitals,)
)