In [16]:
import requests 
from datetime import datetime, timezone
import pandas as pd

def get_metar_data(id="EGLC"):
    response = requests.get(
        'https://aviationweather.gov/api/data/metar',
        params={'ids': id, 'format': 'json'}
    )
    data = response.json()
    return data

"""
Found the ID at: https://aviationweather.gov/
"""

## london ID
id = "EPWA"
response = requests.get(
    'https://aviationweather.gov/api/data/metar',
    params={'ids': id, 'format': 'json'}
)

data = response.json()


# df = pd.DataFrame().from_dict(data)

# warsaw_tz = zoneinfo.ZoneInfo("Europe/Warsaw")

# ## convert the time of the observation to dateitme
# df['obsTime'] = df['obsTime'].apply(
#     lambda x: datetime.fromtimestamp(int(x), tz=warsaw_tz)
# )

# df['reportTime'].apply(
#     lambda x: datetime.fromtimestamp(x, tz=warsaw_tz)
# )

# ## filter only the selected rows
# df = df[['icaoId','obsTime','reportTime','temp','dewp','wdir','wspd','qcField']]
# df

In [17]:
data

[{'icaoId': 'EPWA',
  'receiptTime': '2026-03-26T12:02:17.627Z',
  'obsTime': 1774526400,
  'reportTime': '2026-03-26T12:00:00.000Z',
  'temp': 9,
  'dewp': 0,
  'wdir': 350,
  'wspd': 9,
  'visib': '6+',
  'altim': 1005,
  'qcField': 16,
  'metarType': 'METAR',
  'rawOb': 'METAR EPWA 261200Z 35009KT 320V020 9999 FEW033 09/00 Q1005 NOSIG',
  'lat': 52.163,
  'lon': 20.961,
  'elev': 107,
  'name': 'Warsaw/Chopin Arpt, MZ, PL',
  'cover': 'FEW',
  'clouds': [{'cover': 'FEW', 'base': 3300}],
  'fltCat': 'VFR'}]

In [ ]:
import zoneinfo  

warsaw_tz = zoneinfo.ZoneInfo("Europe/Warsaw")

df['obsTime'] = df['obsTime'].apply(
    lambda x: datetime.fromtimestamp(int(x), tz=warsaw_tz)
)

In [12]:
df

,icaoId,obsTime,reportTime,temp,dewp,wdir,wspd,qcField
0,EPWA,2026-03-26 13:00:00+01:00,2026-03-26T12:00:00.000Z,9,0,350,9,16

In [8]:
df = pd.DataFrame().from_dict(data)

## convert the time of the observation to dateitme
df['obsTime'] = df['obsTime'].apply(lambda x: datetime.fromtimestamp(int(x),
                                                                        tz = timezone.utc))

## filter only the selected rows
df = df[['icaoId','obsTime','reportTime','temp','dewp','wdir','wspd','qcField']]

In [10]:
datetime.fromtimestamp(data[0].get('obsTime'))

datetime.datetime(2026, 3, 26, 13, 0)

In [8]:
data[0].get('obsTime')

1774526400

In [71]:
df.head()

,icaoId,obsTime,reportTime,temp,dewp,wdir,wspd,qcField
0,EGLC,2026-03-22 13:20:00+00:00,2026-03-22T13:20:00.000Z,12,4,210,5,2

In [72]:
pd.to_datetime(df['obsTime'], utc=True)

0   2026-03-22 13:20:00+00:00
Name: obsTime, dtype: datetime64[ns, UTC]

In [17]:
datetime.now().strftime("%H:%M:%S")

'13:20:45'

In [1]:
import numpy as np 
def get_metar_data(id="EGLC"):
    response = requests.get(
        'https://aviationweather.gov/api/data/metar',
        params={'ids': id, 'format': 'json'}
    )
    data = response.json()
    return data

def make_df_metar(data):
    df = pd.DataFrame().from_dict(data)

    ## convert the time of the observation to dateitme
    df['obsTime'] = df['obsTime'].apply(lambda x: datetime.fromtimestamp(int(x),
                                                                            tz = timezone.utc))

    ## filter only the selected rows
    df = df[['icaoId','obsTime','reportTime','temp','dewp','wdir','wspd','qcField']]

    return df

In [1]:
import time
from datetime import datetime, timezone
import numpy as np
import requests
import pandas as pd
reference_minutute = np.array([20,50])

import numpy as np 
def get_metar_data(id="EGLC"):
    response = requests.get(
        'https://aviationweather.gov/api/data/metar',
        params={'ids': id, 'format': 'json'}
    )
    data = response.json()
    return data

def make_df_metar(data):
    df = pd.DataFrame().from_dict(data)

    ## convert the time of the observation to dateitme
    df['obsTime'] = df['obsTime'].apply(lambda x: datetime.fromtimestamp(int(x),
                                                                            tz = timezone.utc))

    ## filter only the selected rows
    df = df[['icaoId','obsTime','reportTime','temp','dewp','wdir','wspd','qcField']]

    return df

## GET TIME NOW 
actual = datetime.now()
print(f"TIME NOW:{actual.strftime('%H:%M:%S')}")
actual_minute =actual.minute
correct_min_evaluate = reference_minutute[np.argmin(np.abs(reference_minutute - actual_minute))]

## FIRST API CALL 
data = get_metar_data()
obstime = datetime.fromtimestamp(int(data[0].get('obsTime')),tz = timezone.utc)

while obstime.minute != correct_min_evaluate:
    print(f"Waiting for the right minute: {correct_min_evaluate} - actual minute: {obstime.minute}")
    data = get_metar_data()
    obstime = datetime.fromtimestamp(int(data[0].get('obsTime')),tz = timezone.utc)
    time.sleep(15)

## pass to a df 
df = make_df_metar(data)
df.head()

TIME NOW:14:13:28
Waiting for the right minute: 20 - actual minute: 50
Waiting for the right minute: 20 - actual minute: 50

KeyboardInterrupt:

In [32]:
data = get_metar_data()

In [33]:
data.get('ObsTime')

AttributeError: 'list' object has no attribute 'get'

In [40]:

obstime = datetime.fromtimestamp(int(data[0].get('obsTime')),tz = timezone.utc)
obstime.minute

50

In [ ]:
data[0]data[0]

{'icaoId': 'EGLC',
 'receiptTime': '2026-02-25T11:54:29.484Z',
 'obsTime': 1772020200,
 'reportTime': '2026-02-25T12:00:00.000Z',
 'temp': 16,
 'dewp': 11,
 'wdir': 220,
 'wspd': 6,
 'visib': '6+',
 'altim': 1015,
 'qcField': 2,
 'metarType': 'METAR',
 'rawOb': 'METAR EGLC 251150Z AUTO 22006KT 190V260 9999 NCD 16/11 Q1015',
 'lat': 51.505,
 'lon': 0.055,
 'elev': 10,
 'name': 'London City Arpt, EN, GB',
 'cover': 'CLR',
 'clouds': [],
 'fltCat': 'VFR'}