In [60]:
import requests 
from datetime import datetime, timezone
import pandas as pd

"""
Found the ID at: https://aviationweather.gov/
"""

## london ID
id = "EGLC"
response = requests.get(
    'https://aviationweather.gov/api/data/metar',
    params={'ids': id, 'format': 'json'}
)

data = response.json()


print(data)

[{'icaoId': 'EGLC', 'receiptTime': '2026-02-17T14:54:25.171Z', 'obsTime': 1771339800, 'reportTime': '2026-02-17T15:00:00.000Z', 'temp': 6, 'dewp': -5, 'wdir': 300, 'wspd': 8, 'visib': '6+', 'altim': 1016, 'qcField': 2, 'metarType': 'METAR', 'rawOb': 'METAR EGLC 171450Z AUTO 30008KT 270V330 9999 NCD 06/M05 Q1016', 'lat': 51.505, 'lon': 0.055, 'elev': 10, 'name': 'London City Arpt, EN, GB', 'cover': 'CLR', 'clouds': [], 'fltCat': 'VFR'}]

In [61]:
df = pd.DataFrame().from_dict(data)

## convert the time of the observation to dateitme
df['obsTime'] = df['obsTime'].apply(lambda x: datetime.fromtimestamp(int(x),
                                                                        tz = timezone.utc))

## filter only the selected rows
df = df[['icaoId','obsTime','reportTime','temp','dewp','wdir','wspd','qcField']]

In [62]:
df.head()

,icaoId,obsTime,reportTime,temp,dewp,wdir,wspd,qcField
0,EGLC,2026-02-17 14:50:00+00:00,2026-02-17T15:00:00.000Z,6,-5,300,8,2

In [27]:
df.head()

  icaoId                   obsTime  temp  dewp  wdir  wspd  qcField
0   EGLC 2026-02-16 16:50:00+00:00     8     3   280    16        2

In [14]:
pd.to_datetime(df['obsTime'], utc=True)

0   1970-01-01 00:00:01.771260600+00:00
Name: obsTime, dtype: datetime64[ns, UTC]