In [20]:
# Python Standard Libraries
import os
import zipfile
import urllib.request

# Data Manipulation Libraries
import numpy as np
import pandas as pd
import xarray as xr
import dask
import rioxarray 
from dask.diagnostics.progress import ProgressBar

from dotenv import load_dotenv
dask.config.set(**{"array.slicing.split_large_chunks": True})
xr.set_options(keep_attrs=True)

In [21]:
load_dotenv()

True

In [22]:
PAT = os.environ.get("earth_data_hub")

In [23]:
ds = xr.open_dataset(
    f"https://edh:{PAT}@data.earthdatahub.destine.eu/era5/reanalysis-era5-land-no-antartica-v0.zarr",
    chunks={},
    engine="zarr",
)

## time slice 
ds_hourly = ds.sel(valid_time = slice("2020-01-01", "2021-01-01")).sel(latitude=51.505, longitude=0.055, method="nearest")


## convert CELCIUS
t2m = ds_hourly.t2m.astype("float32") - 273.15
t2m.attrs["units"] = "°C"

In [10]:
VARIABLES = ["t2m", "ssrd"]  # add d2m for dewpoint if needed

ds_point = xr.open_dataset(
        f"https://edh:{PAT}@data.earthdatahub.destine.eu/era5/reanalysis-era5-land-no-antartica-v0.zarr",
        chunks={"valid_time": 24 * 30},   # chunk by ~1 month of hours
        engine="zarr",
    )[VARIABLES]

/tmp/ipykernel_332377/2052227096.py:3: UserWarning: The specified chunks separate the stored chunks along dimension "valid_time" starting at index 720. This could degrade performance. Instead, consider rechunking after loading.
  ds_point = xr.open_dataset(

In [24]:
ds

<xarray.Dataset> Size: 708TB
Dimensions:              (valid_time: 667632, latitude: 1472, longitude: 3600)
Coordinates:
  * valid_time           (valid_time) datetime64[ns] 5MB 1950-01-01 ... 2026-...
  * latitude             (latitude) float64 12kB 90.0 89.9 89.8 ... -57.0 -57.1
  * longitude            (longitude) float64 29kB 0.0 0.1 0.2 ... 359.8 359.9
    depthBelowLandLayer  float64 8B ...
    number               int64 8B ...
    surface              float64 8B ...
Data variables: (12/50)
    asn                  (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    d2m                  (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    e                    (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    es                   (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    evabs                (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    evaow                (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    ...                   ...
    swvl4                (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    t2m                  (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    tp                   (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    tsn                  (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    u10                  (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
    v10                  (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(2880, 64, 64), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-10-29T11:44 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

In [11]:
ds_point

<xarray.Dataset> Size: 28TB
Dimensions:              (valid_time: 667632, latitude: 1472, longitude: 3600)
Coordinates:
  * valid_time           (valid_time) datetime64[ns] 5MB 1950-01-01 ... 2026-...
  * latitude             (latitude) float64 12kB 90.0 89.9 89.8 ... -57.0 -57.1
  * longitude            (longitude) float64 29kB 0.0 0.1 0.2 ... 359.8 359.9
    depthBelowLandLayer  float64 8B ...
    number               int64 8B ...
    surface              float64 8B ...
Data variables:
    t2m                  (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(720, 64, 64), meta=np.ndarray>
    ssrd                 (valid_time, latitude, longitude) float32 14TB dask.array<chunksize=(720, 64, 64), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_edition:            1
    GRIB_subCentre:          0
    history:                 2024-10-29T11:44 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             European Centre for Medium-Range Weather Forecasts

### Check the parquet

In [25]:
import pandas as pd
import numpy as np

In [155]:
df = pd.read_parquet("/home/camarada/Documents/projects/temp-grss-nasa/daily_max_temp/explore_temp_and_time_distribution/era5_london_clima/era5_2021.parquet")

In [27]:
df.shape

(8760, 10)

In [28]:
df.columns

Index(['datetime', 't2m', 'ssrd', 'sshf', 'slhf', 'skt', 'stl1', 'sp', 'u10',
       'v10'],
      dtype='object')

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  8760 non-null   datetime64[ns]
 1   t2m       8760 non-null   float32
 2   ssrd      8760 non-null   float32
 3   sshf      8760 non-null   float32
 4   slhf      8760 non-null   float32
 5   skt       8760 non-null   float32
 6   stl1      8760 non-null   float32
 7   sp        8760 non-null   float32
 8   u10       8760 non-null   float32
 9   v10       8760 non-null   float32
dtypes: datetime64[ns](1), float32(9)
memory usage: 376.5 KB

In [30]:
df.head()

,datetime,t2m,ssrd,sshf,slhf,skt,stl1,sp,u10,v10
0,2021-01-01 00:00:00,0.100006,3717120.0,134016.0,-780288.0,-0.649994,1.100006,100544.0,1.347656,-1.293945
1,2021-01-01 01:00:00,-0.149994,0.0,-112016.0,768864.0,-0.649994,1.100006,100544.0,1.179688,-1.620117
2,2021-01-01 02:00:00,-0.399994,0.0,38128.0,-2616.0,-1.149994,0.850006,100608.0,1.193359,-1.665039
3,2021-01-01 03:00:00,-1.149994,0.0,42720.0,3640.0,-1.899994,0.600006,100672.0,1.398438,-1.484375
4,2021-01-01 04:00:00,-1.399994,0.0,37312.0,3036.0,-2.399994,0.600006,100672.0,1.603516,-1.289062

In [19]:
df.tail()

                datetime       t2m  ssrd
8779 2004-12-31 19:00:00  7.350006   0.0
8780 2004-12-31 20:00:00  6.600006   0.0
8781 2004-12-31 21:00:00  5.350006   0.0
8782 2004-12-31 22:00:00  4.850006   0.0
8783 2004-12-31 23:00:00  4.600006   0.0

In [57]:
df_filter = df.loc[df['datetime'].dt.date == pd.Timestamp("2021-07-19").date()]

In [34]:
df['datetime'].dt.date

0       2021-01-01
1       2021-01-01
2       2021-01-01
3       2021-01-01
4       2021-01-01
           ...
8755    2021-12-31
8756    2021-12-31
8757    2021-12-31
8758    2021-12-31
8759    2021-12-31
Name: datetime, Length: 8760, dtype: object

In [37]:
pd.Timestamp("2021-07-19").date()

datetime.date(2021, 7, 19)

In [ ]:
df_wu = pd.read_csv

In [45]:
from pathlib import Path
from datetime import date

In [66]:
root = Path("/home/camarada/Documents/projects/temp-grss-nasa/data_/wunderground/processed")


target_date = date(2021, 7, 19)
file_path = (
    root
    / f"{target_date:%Y}"
    / f"{target_date:%m}"
    / f"EGLC_{target_date:%Y_%m_%d}.parquet"
)

In [67]:
df_wu = pd.read_parquet(file_path)

In [51]:
df_wu.head()

,Time,Temperature,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Precip.,Condition,datetime
0,11:20 PM,64.0,59.0,83.0,SW,6.0,0.0,30.16,0.0,Fair,2021-07-09 23:20:00
1,11:50 PM,64.0,59.0,83.0,SW,5.0,0.0,30.16,0.0,Fair,2021-07-09 23:50:00
2,12:20 AM,63.0,59.0,88.0,SW,5.0,0.0,30.13,0.0,Fair,2021-07-09 00:20:00
3,12:50 AM,63.0,59.0,88.0,WSW,6.0,0.0,30.13,0.0,Fair,2021-07-09 00:50:00
4,1:20 AM,63.0,57.0,82.0,SW,8.0,0.0,30.13,0.0,Fair,2021-07-09 01:20:00

In [56]:
df_wu.shape

(48, 11)

In [50]:
import altair

In [92]:
dff = pd.concat([
    df_filter[['datetime','t2m']].set_index('datetime'),
    df_wu[['datetime','Temperature']].set_index(['datetime'])
],
    join='outer')

## convert farehait to celcius
dff['Temperature'] = (dff['Temperature'] - 32) * (5/9)

## modify name
dff = dff.rename(columns={'Temperature':'WUnder',
            't2m':'ERA5'})

In [ ]:
dff['Temperature'] = (dff['Temperature'] - 32) * (5/9)

In [93]:
dff

                          ERA5     WUnder
datetime
2021-07-19 00:00:00  19.100006        NaN
2021-07-19 01:00:00  18.350006        NaN
2021-07-19 02:00:00  17.850006        NaN
2021-07-19 03:00:00  17.350006        NaN
2021-07-19 04:00:00  16.850006        NaN
...                        ...        ...
2021-07-19 20:50:00        NaN  21.111111
2021-07-19 21:20:00        NaN  21.111111
2021-07-19 21:50:00        NaN  20.000000
2021-07-19 22:20:00        NaN  20.000000
2021-07-19 22:50:00        NaN  18.888889

[72 rows x 2 columns]

In [83]:
dff.sort_index().reset_index().melt(id_vars = ['datetime'])

               datetime     variable      value
0   2021-07-19 00:00:00          t2m  19.100006
1   2021-07-19 00:20:00          t2m        NaN
2   2021-07-19 00:50:00          t2m        NaN
3   2021-07-19 01:00:00          t2m  18.350006
4   2021-07-19 01:20:00          t2m        NaN
..                  ...          ...        ...
139 2021-07-19 22:20:00  Temperature  64.800000
140 2021-07-19 22:50:00  Temperature  61.200000
141 2021-07-19 23:00:00  Temperature        NaN
142 2021-07-19 23:20:00  Temperature  64.800000
143 2021-07-19 23:50:00  Temperature  68.400000

[144 rows x 3 columns]

In [108]:
altair.Chart(
    dff.groupby(pd.Grouper(freq='1h'),
                sort=True).mean().reset_index().melt(id_vars = ['datetime'])
).mark_line(point=True).encode(
    altair.X('hours(datetime):O').axis(tickMinStep=1),
    y = "value",
    color="variable:N",
    ##shape = 'variable:N'
)

alt.Chart(...)

In [ ]:
import polars as pl

yearr = 2024
RAW_DIR = Path(f"/home/camarada/Documents/projects/temp-grss-nasa/data_/wunderground/processed/{yearr}")
year = sorted(RAW_DIR.rglob("*.parquet"))

# 1. Load all years at once — Polars handles this efficiently
df_wupl = pl.scan_parquet(year).select(
                (pl.col("Temperature").sub(32).mul((5/9)).alias("WU_temp"), ## convert to celcius
                pl.col("datetime"))
                ).collect()

df_wupl = df_wupl.to_pandas()

In [161]:
yearr = 2024
df = pd.read_parquet(f"/home/camarada/Documents/projects/temp-grss-nasa/daily_max_temp/explore_temp_and_time_distribution/era5_london_clima/era5_{yearr}.parquet")
df_filter = df.loc[df['datetime'].dt.year == pd.Timestamp('2024-01-01').year]

In [175]:
dff = pd.concat([
    df_filter[['datetime','t2m']].set_index('datetime'),
    df_wupl[['datetime','WU_temp']].set_index(['datetime']).resample('1h').mean()
],
    axis=1)

## modify name
dff = dff.rename(columns={
            't2m':'ERA5',
            'WU_temp':'WeaUnder'})

In [176]:
pd.read_csv(data.seattle_weather.url)

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [178]:
dff['diff'] = dff['WeaUnder'] -  dff['ERA5']

In [192]:
dff.reset_index()["datetime"].dt.month.map(season_map)

0       winter
1       winter
2       winter
3       winter
4       winter
         ...
8779    winter
8780    winter
8781    winter
8782    winter
8783    winter
Name: datetime, Length: 8784, dtype: object

In [191]:
season_map = {
    12: "winter", 1: "winter", 2: "winter",
    3: "spring", 4: "spring", 5: "spring",
    6: "summer", 7: "summer", 8: "summer",
    9: "autumn", 10: "autumn", 11: "autumn"
}

dff["season"] = dff.reset_index()["datetime"].dt.month.map(season_map).values

In [203]:
dff.reset_index().drop(columns=['ERA5','WeaUnder']).melt(id_vars=['datetime','season'],
                                                                value_vars=['diff']   )

                datetime  season variable     value
0    2024-01-01 00:00:00  winter     diff  1.538883
1    2024-01-01 01:00:00  winter     diff  1.233327
2    2024-01-01 02:00:00  winter     diff  0.865272
3    2024-01-01 03:00:00  winter     diff  2.038883
4    2024-01-01 04:00:00  winter     diff  1.639577
...                  ...     ...      ...       ...
8779 2024-12-31 19:00:00  winter     diff  1.778466
8780 2024-12-31 20:00:00  winter     diff  1.778466
8781 2024-12-31 21:00:00  winter     diff  1.528466
8782 2024-12-31 22:00:00  winter     diff  1.559716
8783 2024-12-31 23:00:00  winter     diff  1.465966

[8784 rows x 4 columns]

In [209]:
source

     season   datetime     value
0    autumn 2024-09-01  0.364114
1    autumn 2024-09-02  0.398258
2    autumn 2024-09-03  1.072737
3    autumn 2024-09-04  0.591111
4    autumn 2024-09-05 -0.275787
..      ...        ...       ...
636  winter 2024-12-27 -0.096968
637  winter 2024-12-28 -0.139503
638  winter 2024-12-29 -0.383282
639  winter 2024-12-30  1.284253
640  winter 2024-12-31  1.334311

[641 rows x 3 columns]

In [218]:


source = (
        (dff.reset_index().drop(
            columns=['ERA5','WeaUnder']
            ).melt(id_vars=['datetime','season'],
                value_vars=['diff']   
                )[["datetime", "season", "value"]])
        .reset_index()
       .set_index("datetime")
       .groupby("season")
       .resample("1D")["value"]
       .mean()
       .reset_index()
)
step = 80
overlap = 0.5

chart = (
    alt.Chart(source, height=step, width=600)
    .transform_bin(
        ["bin_max", "bin_min"], "value"
    )
    .transform_aggregate(
        value="count()",
        groupby=["season", "bin_min", "bin_max"]
    )
    .transform_impute(
        impute="value",
        groupby=["season"],
        key="bin_min",
        value=0
    )
    .mark_area(
        interpolate="monotone",
        fillOpacity=0.8,
        stroke="lightgray",
        strokeWidth=0.5,
        clip=True
    )
    .encode(
        alt.X("bin_min:Q", title="Temperature Difference"),
        alt.Y(
            "value:Q",
            axis=None,
            scale=alt.Scale(range=[step, -step * overlap])
        ),
        alt.Color("season:N")
    )
    .facet(
        row=alt.Row(
            "season:N",
            header=alt.Header(labelAngle=0, labelAlign="left")
        )
    )
    .configure_facet(spacing=0)
    .configure_view(stroke=None)
)

chart

alt.FacetChart(...)

In [219]:

alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

In [220]:
source = (
    dff.reset_index()
       .drop(columns=['ERA5','WeaUnder'])
       .melt(
            id_vars=['datetime','season'],
            value_vars=['diff']
        )[["datetime", "value"]]
)

source["month"] = source["datetime"].dt.month

In [226]:
step = 12
overlap = 0.2

chart = (
    alt.Chart(source, height=step, width=800)
    .transform_bin(
        ["bin_max", "bin_min"], "value"
    )
    .transform_aggregate(
        value="count()",
        groupby=["month", "bin_min", "bin_max"]
    )
    .transform_impute(
        impute="value",
        groupby=["month"],
        key="bin_min",
        value=0
    )
    .mark_area(
        interpolate="monotone",
        fillOpacity=0.8,
        stroke="lightgray",
        strokeWidth=0.5,
        clip=True
    )
    .encode(
        alt.X(
            "bin_min:Q",
            title="Temperature Difference",
            axis=alt.Axis(tickCount=6)
        ),
        alt.Y(
            "value:Q",
            axis=None,
            scale=alt.Scale(range=[step, -step * overlap])
        ),
        alt.Color("month:O")
    )
    .facet(
        row=alt.Row(
            "month:O",
            sort=list(range(1,13)),
            header=alt.Header(labelAngle=0)
        )
    )
    .configure_facet(spacing=0)
    .configure_view(stroke=None)
)

chart

alt.FacetChart(...)